server:
  port: 8080
spring:
  datasource:
     hikari:
       driver-class-name: com.mysql.cj.jdbc.Driver
       ##로컬에서 디비연결
       jdbc-url: jdbc:mysql://localhost:3306/rest_api?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
       username: root
       password: auddnjs20
     #배포시 디비
#     jdbc-url: jdbc:mysql://mydb.c72ss0somxra.ap-northeast-2.rds.amazonaws.com:3306/project?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#     username: ${MYSQL_ID}
#     password: ${MYSQL_PWD}